version: 0.2

phases:
  install:
    commands:
      - cd CodePipeline
      - echo Installing Node.js dependencies...
      - npm install
  build:
    commands:
      - echo Building the application...
      - npm run build
  post_build:
    commands:
      - echo Build completed!
artifacts:
  files:
    - '**/*'
